## Setup a model to encode particle types into a vector embedding
## so that particles in the same events are close to each other
## in the embedding space.

_target_: hadml.models.node_embedding_module.ParticleEmbeddingModule